version: "3.8"

services:
  nagios:
    image: ghcr.io/hosted-domains/nagios-docker:latest
    environment:
      - SERVICE_NAME=app
      - SERVICE_PORT=80
    ports:
      - "80:80"

  app:
    image: your-app-image
