FROM manios/nagios:latest

LABEL org.opencontainers.image.source="https://github.com/hosted-domains/nagios-docker"

RUN apk add --no-cache \
    bash bc date file nmap openssl mariadb-client\
    curl \
    tzdata \
